name: Gorson Docker Dev Image Build and Publish

on:
  push:
    branches:
      - '**'
      - '!main'

permissions:
  id-token: write
  contents: read

jobs:
  code-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Run tests
        run: ./scripts/test.sh

  image-build-and-publish:
    runs-on: ubuntu-latest
    needs: code-test
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Log in to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Build Docker image
        run: docker build -f Dockerfile.github -t ${{ secrets.AWS_ECR_PUBLIC_URI }}:dev .
      - name: Push Docker image
        run: docker push ${{ secrets.AWS_ECR_PUBLIC_URI }}:dev

  image-test:
    runs-on: ubuntu-latest
    needs: image-build-and-publish
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Log in to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
      - name: Test Docker image build
        run: |
          docker build -f Dockerfile.github-test -t gorson-test .
          docker run --rm gorson-test
